// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJYQjwe7yE-Kaj9wvPy-pBKW7LbWlDx8',
    appId: '1:883276103642:web:c5cbd1c11ec464a1cfcae3',
    messagingSenderId: '883276103642',
    projectId: 'emergency-sos-b8ae6',
    authDomain: 'emergency-sos-b8ae6.firebaseapp.com',
    databaseURL: 'https://emergency-sos-b8ae6-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-sos-b8ae6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJYQjwe7yE-Kaj9wvPy-pBKW7LbWlDx8',
    appId: '1:883276103642:android:temp_placeholder',
    messagingSenderId: '883276103642',
    projectId: 'emergency-sos-b8ae6',
    databaseURL: 'https://emergency-sos-b8ae6-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-sos-b8ae6.firebasestorage.app',
  );
}
